### PR TITLE
Android dependencies

### PR DESCRIPTION
**Pull request by RblSb**
Usage: (OUTDATED!)
```js
project.targetOptions.android_native.dependencies = `
implementation 'com.android.billingclient:billing:2.0.0'
`;
```

### CODE REVIEW

**Comment by RblSb** [comment]
I need also options.globalDependencies to change global build.gradle for some libs. Should i do this, or just add way to set custom gradle.build files?

**Comment by RblSb** [comment]
Same for proguard rules, custom file path option or function like in this pr?

**Comment by RblSb** [comment]
Props added:
```
buildGradlePath
globalBuildGradlePath
proguardRulesPath
customFilesPath
```
Now you can set paths to `build.gradle`/` proguard-rules` templates, or completed configs with some changes. To push additional files or replace `gradle.properties`/etc (not templates, only ready ones) there is `customFilesPath` to folder.
Also made a little refactoring.

**Comment by RblSb** [comment]
Requesting for review, want to publish some lib based on these properties =)

**Comment by RobDangerous** [comment]
I don't understand most of this. I'll trust you on this and merge it (and maybe I'll change all of it when I find some more time for Android).

**Comment by RblSb** [comment]
With these changes you can set custom pathes to android build.gradle files (like Assets-android/myfile.gradle), this is best way to add some dependencies for app, manually. Also you can now set custom folder for configs for these dependencies,  they will be copied in root-level dir for Android Studio project, this is what official library manuals wants from you for setup. Actual example should be here tomorrow.

**Pull request merged**
